<?php
/**
 * Class Application
 * @package Seidelmann\DevUtils
 * @author Sebastian Seidelmann <sebastian.seidelmann@googlemail.com>
 */

namespace Seidelmann\DevUtils;

use Seidelmann\DevUtils\Helper\AbstractHelper;
use Symfony\Component\Console\Application as ConsoleApplication;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class Application
 * @package Seidelmann\DevUtils
 * @author Sebastian Seidelmann <sebastian.seidelmann@googlemail.com>
 */
class Application extends ConsoleApplication
{
    /**
     * Configures the input and output instances based on the user arguments and options.
     *
     * @param InputInterface $input An InputInterface instance
     * @param OutputInterface $output An OutputInterface instance
     */
    protected function configureIO(InputInterface $input, OutputInterface $output)
    {
        foreach ($this->getHelperSet()->getIterator() as $helper) {
            if ($helper instanceof AbstractHelper) {
                $helper->setWorkingDirectory(getcwd() . DIRECTORY_SEPARATOR);
                $helper->setIO($input, $output);
                $helper->init();
            }
        }

        parent::configureIO($input, $output); // TODO: Change the autogenerated stub
    }


}